services:
    backend-despachos:
        build:
            context: ./despachos/Springboot-API-REST-DESPACHO
        container_name: backend-despachos
        ports:
            - "8081:8081"
        depends_on:
            - db-mysql
        environment:
            - DB_ENDPOINT=${DB_ENDPOINT}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}


    backend-ventas:
        build:
            context: ./ventas/Springboot-API-REST
        container_name: backend-ventas
        ports:
            - "8080:8080"
        depends_on:
            - db-mysql
        environment:
            - DB_ENDPOINT=${DB_ENDPOINT}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    db-mysql:
        build:
            context: ./db-mysql
        container_name: db-mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: